version: 1
runners:
  Machine:
    config-id: 2
jobs:
  CatalystDeploy:
    runner: Machine
    steps:
      - npm install -g zcatalyst-cli@latest
      - node --version
      - catalyst deploy --project env.5053000000469105 --org env.60022986418 --env.token m_1004.b2bc22a458932bc8db1f2ff5a5d220ac.3bebac6ce89533b6443f31712d083ddc
stages:
  - name: deploymentStage
    jobs:
      - CatalystDeploy