version: 1
jobs:
 hello:
    steps:
      - echo "Hello"
 world:
    steps:
      - echo "World"
 hello-world:
    steps:
      - echo "Hello World!"
 job1:
    runner: runner1
    image: image1
    cwd: /path
    steps:
      - "jobs:\r"
      - '      -deploy'
 job2:
    steps:
      - >-
        catalyst deploy appsail --name << env.APPLICATION_NAME >> --build-path
        "<< env.PACKAGE_PATH >>" --stack << env.STACK >> --platform <<
        env.PLATFORM >> --command "<< env.STARTUP_COMMAND >>" --verbose
    artifacts:
      download:
        - type: file
          name: SNAPSHOT.jar
          file: /SNAPSHOT.jar
          location: stratus://<< env.BUCKET_NAME >>/
stages:
  - name: build
    jobs:
        - world
  - name: stage1
    jobs:
      - job1
    when:
      equal:
        - << status.build >>
        - success
variables:
  variable1: SHOULD_RUN
images:
  image1:
    image: node:18
    registry: https://registry.npmjs.org/
    auth:
      username: Mahi
      password: user08@elite
runners:
  runner1:
    config-id: 1