version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:18
    registry: https://registry.npmjs.org/
    auth:
      username: env.Mahindha-04
      password: env.M@hindha@28
jobs:
  CatalystDeploy:
    runner: Machine
    image: image
    steps:
      - npm install -g zcatalyst-cli@latest
      - node --version
      - catalyst deploy --project env.5053000000469105 --org env.60022986418 --env.token m_1004.b2bc22a458932bc8db1f2ff5a5d220ac.3bebac6ce89533b6443f31712d083ddc
stages:
  - name: deploymentStage
    jobs:
      - CatalystDeploy